# Generated by Django 4.2.2 on 2023-07-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paymentmethod', '0002_rename_eventpayment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
    ]
