# Generated by Django 4.2.2 on 2023-07-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Speaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='created',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='updated',
        ),
    ]
